language: python
python:
  - "2.7"
install:
  - "pip install ."
  - "pip install icalendar"
  - "pip install pylint"
script: "python setup.py test && pylint --errors-only topydo test"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b7a69031304c472294ac
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
